version: '3.8'
services:
  cyber_api:
    container_name: 'cyber_api'
    #image: cyber_project
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3006:8080'
    volumes:
       - '/home/lyhou/Sonaqube/images:/home/cyber/media'
       - 'home/lyhou/Sonaqube/git_clone_repo:/home/cyber/git_clone_repo'
