server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sona
    username: postgres
    password: lyhou123
    driver-class-name: org.postgresql.Driver

  jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: '/'

sonar:
  token: squ_55caae1ee23e4d6c9ecdaece2796acf29d40c8e7    #squ_fb8b910e970a8269272808486bfb0f111636083e(server)
  url: http://167.172.64.59:3004

my-app:
  state: dev

git:
  clone_directory: /git_clone_repos/

file_storage:
  image_location: "filestorage/images/"
  client_path: "/images/**"


# This is for the access token
ACCESS_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/access-token-private.key
ACCESS_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/access-token-public.key
# This is for the refresh token
REFRESH_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/refresh-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/refresh-token-public.key
